spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
  datasource:
    username: postgres
    password: 1234

    url: jdbc:postgresql://localhost:5432/marketplace
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090
management:
  tracing:
    sampling:
      probability: 1
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

topic:
  order:
    created: order.created